-- ALTER table `CUSTOMER`
--   ADD CONSTRAINT `customer_fk1` FOREIGN KEY (`BId`) REFERENCES `WAREHOUSE`(`BranchId`);


-- ALTER TABLE `PAYMENT_INFORMATION`
--   ADD CONSTRAINT `pay_fk1` FOREIGN KEY(`CId`) REFERENCES `CUSTOMER`(`CustId`),
--   ADD CONSTRAINT `pay_fk2` FOREIGN KEY(`BId`) REFERENCES `WAREHOUSE`(`BranchId`);

-- ALTER TABLE `TRANSACTION_WAREHOUSE_MANUFACTURER`
--   ADD CONSTRAINT `t_fk1` FOREIGN KEY(`ModelId`) REFERENCES `MODEL`(`ModelId`),
--   ADD CONSTRAINT `t_fk2` FOREIGN KEY(`BId`) REFERENCES `WAREHOUSE`(`BranchId`),
--   ADD CONSTRAINT `t_fk3` FOREIGN KEY(`Mid`) REFERENCES `MANUFACTURER`(`Mid`);

-- ALTER TABLE `PROVIDES_SUPPLY`
--     ADD CONSTRAINT `p_fk1` FOREIGN KEY (`BId`) REFERENCES `WAREHOUSE`(`BranchId`),
--     ADD CONSTRAINT `p_fk2` FOREIGN KEY (`ManufacturerId`) REFERENCES `MANUFACTURER`(`Mid`);

ALTER TABLE `STAFF`
    ADD CONSTRAINT `s_fk1` FOREIGN KEY (`BranchId`) REFERENCES `WAREHOUSE`(`BranchId`),
    ADD CONSTRAINT `s_fk2` FOREIGN KEY (`SuperSid`) REFERENCES `STAFF`(`Sid`);

-- ALTER TABLE `STORES_RECORDS_OF_MODELS`
--     ADD CONSTRAINT `m_fk1` FOREIGN KEY (`ModelId`) REFERENCES `MODEL`(`ModelId`),
--     ADD CONSTRAINT `m_fk2` FOREIGN KEY (`RecordId`) REFERENCES `PAYMENT_INFORMATION`(`RecordId`);